"""Add transaction columns to water_data table

Revision ID: cf0fb01c8764
Revises: c61f1ff7221f
Create Date: 2024-08-01 19:17:23.809725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0fb01c8764'
down_revision = 'c61f1ff7221f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_hash', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('amount_sent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amount_received', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_data', schema=None) as batch_op:
        batch_op.drop_column('amount_received')
        batch_op.drop_column('amount_sent')
        batch_op.drop_column('transaction_hash')

    # ### end Alembic commands ###
